export interface Trip {
  _id: string;
  tripName: string;
  tripID: string;
  description: string;
  startingTime: string;
  endingTime: string;
  price: string;
  slots: string[];
  cancellationPolicy: string;
  createdAt: string;
  updatedAt: string;
  tripImage?: string;
}

export interface Payment {
  _id: string;
  paymentId: string;
  amount: string;
  currency: string;
  description: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  processedAt: string;
}
export interface paymentPayload {
  amount: string;
  currency: string;
  description: string;
  trips: any;
}

interface Accommodation {
  name: string;
  description: string;
  imageUrl: string;
  amenities: string[];
}

// Interface for the GalleryCategory object
interface GalleryCategory {
  title: string;
  images: {
    url: string;
    alt?: string;
  }[];
}

export interface TripDetail {
  tripID: string;
  tripName: string;
  description: string;
  price: string;
  tripImage?: string;
  startingTime: Date;
  endingTime: Date;
  location: string;
  groupSize: number;
  cancellationPolicy: { [key: number]: number }[]; // Object with keys as numbers (like { 15: 100, 7: 50, 0: 0 })
  bestTime?: string;
  duration?: string;
  organizerEmail: string;
  slots: Slot[];
  accommodations: Accommodation[];
  galleryCategories: GalleryCategory[];
  createdAt?: Date; // optional, generated by mongoose timestamp
  updatedAt?: Date;
}
